Feature page
talhawaqar/design-teardown pull request #1
Opened 2020-05-20 14:02 UTC by Haroonabdulrazaq

This project is focused on building the design hierarchy as displayed in smashing magazine.
It has a lot of sections like the:
-  Main section
- Text section
- Link section
- Footer section

2020-05-20 14:18 UTC, Haroonabdulrazaq commented
Note: Logo breaks when the network is slow

2020-05-20 18:36 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-20 19:01 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great work with this great project :+1: Let us improve our code and make it even better.Kindly address the comments below: :slightly_smiling_face: 

- ```Nav```, each of the nav items uses div for positioning
![ccp](https://user-images.githubusercontent.com/46388113/82484506-87764300-9ac9-11ea-9bff-699d90d1bb1e.png)
```Currently``` this is what we have
![ccp1](https://user-images.githubusercontent.com/46388113/82484588-a674d500-9ac9-11ea-8700-56717a665b8a.png)
- ```3 articles rows```
![gcc](https://user-images.githubusercontent.com/46388113/82484937-331f9300-9aca-11ea-8c53-a9ebf71321d0.png)
- There is a lot of repeating codes in our CSS file, let us apply the DRY rule. For more info kindly check this [article](https://speckyboy.com/good-bad-css-practices/)
- Kindly use float property for positioning some of the elements

Kindly implement these changes and submit another code review
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-20 19:01 UTC, addod19 commented on index.html
> +          <div class="main-content-div medium-gray">
Kindly use``` <article> instead of <div class="main-content-div medium-gray">```

2020-05-20 19:01 UTC, addod19 commented on index.html
> +          <div class="main-content-div dark-gray">
Kindly use ```<article> instead of <div class="main-content-div dark-gray">```

2020-05-21 18:23 UTC, rammazzoti2000 requested changes
### Hello team :wave: awesome project, great job :rocket: :tada: 
You guys did a great work also trying to implement some of the changes required by the previous TSE like using float on some of the elements, the three article rows and wrapping the nav elements inside div tag for positioning.
There are still some issues left that are preventing me from approving this project
### :stop_sign: Requires Changes :construction: :construction_worker: 
- [ ] The change required by the previous TSE related to the repeating codes in the CSS file have not been implemented although your last commit says you did so, please kindly apply the DRY rule for repeating styling rules. For more info kindly check this [article](https://speckyboy.com/good-bad-css-practices/)
- [ ] You still have to implement the change required by the previous TSE  by using `<article>` instead of `<div class="main-content-div dark-gray">` around line 93 in html file
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-21 18:23 UTC, rammazzoti2000 commented on index.html
> +          <div class="main-content-div dark-gray">
Kindly implement the change required by the previous TSE

2020-05-22 09:03 UTC, Haroonabdulrazaq commented
We have fixed all repeating properties which have the same value

2020-05-23 03:23 UTC, sumancrest0001 approved these changes
****STATUS: APPROVED :100: 
Congratulation TEAM :clap: :clap: :+1:**** 
You have done a great job to fix issues raised by the previous TSEs. It looks good to me and it's a green signal from my side. Now, You can merge the PR to master and move to the next project.

**Happy coding!!!**

2020-05-23 08:19 UTC, Haroonabdulrazaq commented
Thanks for taking the time to review our code :+1

On Saturday, May 23, 2020, Sman Shrestha <notifications@github.com> wrote:

> *@sumancrest0001* approved this pull request.
>
>
> *STATUS: APPROVED 💯 Congratulation TEAM 👏 👏 👍*
> You have done a great job to fix issues raised by the previous TSEs. It
> looks good to me and it's a green signal from my side. Now, You can merge
> the PR to master and move to the next project.
>
> *Happy coding!!!*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/talhawaqar/design-teardown/pull/1#pullrequestreview-417246133>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMDDA27ZTB3QU2JHGEJJH73RS46SZANCNFSM4NF63HQQ>
> .
>

2020-05-23 09:18 UTC, merged